### ISSUE TITLE
Another Strange Problem

### ISSUE THREAD

**Issue by queejie** [greim/html-tokenizer#4]
I'm not sure why, but the following line:

`const defaultEntityMap = require('./default-entity-map');
`

doesn't work when compiling with Angular/Webpack.  The implicit .json extension isn't recognized, and  I'm not sure why, since it is using node.

Would it be possible to add the .json to your code base, by any chance? I'm trying to avoid having a separate copy of the code just to allow this to work.

Thanks very much for this module.

**Comment by greim** [comment]
Hrm, using this project with WebPack has been working for me. Looking at my config, I have .json in my resolve.extensions:

```js
extensions: ['.js', '.json', '.ts', '.tsx'],
```

Have you tried adding that?
